# action.yml
name: 'Run Scala Checkstyle'
description: 'Run scalastyle to checkstyle code'
branding:
  icon: 'code'  
  color: 'red'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  checkstyle_version:
    description: 'Scalastyle version to be used [2.10,2.11,2.12]'
    default: '2.12'
  workdir:
    description: 'Directory with scala code'
    default: '.'
  scalastyle_path:
    description: 'Path to scalastyle configuration'
    default: 'NONE'
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'reviewdog'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'warning'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review]'
    default: 'github-check'
  debug:
    description: 'Enable or disable debug [true,false]'
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'