# action.yml
name: 'Run Scala Checkstyle'
description: 'Run scalastyle to checkstyle code'
branding:
  icon: 'code'  
  color: 'red'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  version:
    description: 'Scalastyle version to be used [2.10,2.11,2.12]'
    default: '2.12'
  workdir:
    description: 'Directory with scala code'
    default: '.'
  scalastyle_path:
    description: 'Path to scalastyle configuration'
    default: 'NONE'
runs:
  using: 'docker'
  image: 'Dockerfile'