name: Build and Test
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build_job:
    runs-on: ubuntu-latest 
    name: Hello Job
    steps:
    - name: Checkstyle test
      uses: andre-santos-fd/scalastyle_action@main
