name: Scalastyle
on: [pull_request]

jobs:
  Checkstyle:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
              
      - name: Scala Checkstyle
        uses: andre-santos-fd/scalastyle_action@main
        with:
          tool_name: 'scalastyle'
          reporter: 'github-pr-review'   
          github_token: ${{ secrets.github_token }}
          debug: "false"